[package]
name = "fake"
version.workspace = true
edition.workspace = true

[dependencies]
argh = "0.1.10"
cranelift-entity = "0.103.0"
serde = { version = "1.0", features = ["derive"] }
figment = { version = "0.10.12", features = ["toml"] }
anyhow.workspace = true
